name: Every Minute Sheet Check

on:
  schedule:
    - cron: "* * * * *"  # ⏱️ Runs every minute (UTC)
  workflow_dispatch:       # Manual trigger for testing

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to check_updates endpoint
        run: |
          echo "Triggered at $(date -u)"
          curl -X GET "https://sheet-monitoring.onrender.com/dashboard/online_sheets/check_updates_all" -v
